server:
  port: 5000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          # Employee Management Service Route (Data Endpoints)
          - id: employee-service
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/api/employees/**
            filters:
            - StripPrefix=1
            - PrefixPath=/api/v1

          # Employee Management Service OpenAPI Docs Route
          - id: employee-service-api-docs
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/employee/docs
            filters:
            - RewritePath=/employee/docs, /api/v1/swagger-ui/index.html

          # Employee Management Service OpenAPI Docs Assets Route
          - id: employee-service-api-docs-assets
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/employee/**
            filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/swagger-ui

          # Employee Management Service OpenAPI Docs Specs Route
          - id: emp-mgmt-sys-openapi-definition
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/api/v1/v3/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
