server:
  port: 8082

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true      # Automatically maps services from Eureka
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employees/**
          filters:
            - StripPrefix=1

    config:
      fail-fast: true
      retry:
        max-attempts: 5
        multiplier: 1.5
        initial-interval: 2000
        max-interval: 10000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO
