server:
  port: 5000

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
          # Employee Management Service Route (Data Endpoints)
          - id: employee-service
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/api/employees/**
            filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
            - Jwt

          - id: department-service
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/api//departments/**
            filters:
            - StripPrefix=1
            - PrefixPath=/api/v1
            - Jwt

          # Employee Management Service OpenAPI Docs Route
          - id: employee-service-api-docs
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/employee/docs
            filters:
            - RewritePath=/employee/docs, /api/v1/swagger-ui/index.html

          # Employee Management Service OpenAPI Docs Assets Route
          - id: employee-service-api-docs-assets
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/employee/**
            filters:
            - StripPrefix=1
            - PrefixPath=/api/v1/swagger-ui

          # Employee Management Service OpenAPI Docs Specs Route
          - id: emp-mgmt-sys-openapi-definition
            uri: lb://EMP-MGMT-SYS
            predicates:
            - Path=/api/v1/v3/api-docs/**

          # Auth Service Route (Data Endpoints)
          - id: auth-service
            uri: lb://AUTH-SERVICE
            predicates:
            - Path=/api/auth/**
            filters:
            - StripPrefix=1
            - PrefixPath=/

          # Auth Service OpenAPI Docs Route
          - id: auth-service-api-docs
            uri: lb://AUTH-SERVICE
            predicates:
            - Path=/auth/docs
            filters:
            - RewritePath=/auth/docs, /swagger-ui/index.html

          # Auth Service OpenAPI Docs Assets Route
          - id: auth-service-api-docs-assets
            uri: lb://AUTH-SERVICE
            predicates:
            - Path=/auth/**
            filters:
            - StripPrefix=1
            - PrefixPath=/swagger-ui

          # Auth Service OpenAPI Docs Specs Route
          - id: auth-service-openapi-definition
            uri: lb://AUTH-SERVICE
            predicates:
            - Path=/v3/api-docs/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, info, gateway
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: INFO

auth:
  service:
    url: http://localhost:5000/api/auth
