app:
  name: Authentication Service

server:
  port: 5002

spring:
  jpa:
    hibernate:
      ddl-auto: validate # options: none | validate | update | create | create-drop
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/java?user=postgres&password=rootroot
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, refresh
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs/auth
  swagger-ui:
    url: /v3/api-docs/auth
    operations-sorter: alpha
    tags-sorter: alpha
  servers:
  - url: http://localhost:5000/api/auth
    description: AUTH-SERVICE(Via Gateway)

logging:
  level:
    root: info
