app:
  name: Employee Mgmt Sys (Dev)

spring:
  application:
    baseUrl: http://localhost:5001
  jpa:
    hibernate:
      ddl-auto: validate # options: none | validate | update | create | create-drop
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/java?user=postgres&password=rootroot
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  mvc:
    servlet:
      # Base URL for all REST endpoints + versioning
      path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 5001

springdoc:
  servers:
  - url: http://localhost:5000/api/employees
    description: EMP-MGMT-SYS(Via Gateway)
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    root: info

api-gateway:
  url:
