app:
  name: Employee Mgmt Sys (Dev)

spring:
  application:
    baseUrl: http://localhost:5000
  jpa:
    hibernate:
      ddl-auto: validate # options: none | validate | update | create | create-drop
    show-sql: true
  sql:
    init:
      mode: always

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/emp_mgmt_sys}
    driver-class-name: org.postgresql.Driver

  mvc:
    servlet:
      # Base URL for all REST endpoints + versioning
      path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 5000

springdoc:
  api-docs:
    enabled: true
