app:
  name: Employee Mgmt Sys (Dev)

spring:
  application:
    baseUrl: http://localhost:5000
  jpa:
    hibernate:
      ddl-auto: validate # options: none | validate | update | create | create-drop
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/ems?user=admin_user&password=r00tr00t}
    driver-class-name: org.postgresql.Driver

  mvc:
    servlet:
      # Base URL for all REST endpoints + versioning
      path: /api/v1

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 5000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

logging:
  level:
    root: info
